/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.ConcoursDao;
import dao.ResultatDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import model.Candidat;
import model.Concours;
import model.Resultat;
import model.Utilisateur;

/**
 *
 * @author hp
 */

public class FormulaireConcoursFrame extends javax.swing.JFrame {
private Candidat candidat;
private ConcoursDao concoursDao;
private ResultatDao resultatDao;
    private Utilisateur currentUser;

// Modifie cette ligne pour ajouter Utilisateur u
public FormulaireConcoursFrame(Candidat c, Utilisateur u) {
    initComponents();

    this.candidat = c;
    this.currentUser = u; // <--- C'est ici qu'on enregistre l'utilisateur connecté
    this.concoursDao = new ConcoursDao();
    this.resultatDao = new ResultatDao();

    chargerConcours();
}

private void chargerConcours() {

    comboConcours.removeAllItems();

    List<Concours> liste = concoursDao.findAll();

    if (liste != null) {
        for (Concours c : liste) {
            comboConcours.addItem(c);
        }
    }
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboConcours = new javax.swing.JComboBox();
        btnInscrire = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Choisir un concours");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(82, 22, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        comboConcours.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboConcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConcoursActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(88, 36, 0, 68);
        jPanel1.add(comboConcours, gridBagConstraints);

        btnInscrire.setText("S'inscrire");
        btnInscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrireActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 78, 117, 0);
        jPanel1.add(btnInscrire, gridBagConstraints);

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 36, 117, 0);
        jPanel1.add(btnAnnuler, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboConcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConcoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboConcoursActionPerformed

    private void btnInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrireActionPerformed
try {
        // 1. On récupère le concours sélectionné
        Concours selectedConcours = (Concours) comboConcours.getSelectedItem();
        
        if (selectedConcours == null) {
            JOptionPane.showMessageDialog(this, "Veuillez choisir un concours.");
            return;
        }

        // 2. Création du résultat
        Resultat r = new Resultat();
        r.setCandidatId(this.candidat.getId());
        r.setConcoursId(selectedConcours.getId());
        r.setNote(0.0);
        r.setDecision("En attente");

        // 3. Insertion en base
        resultatDao.insert(r);

        // 4. Message et Redirection
        JOptionPane.showMessageDialog(this, "Inscription réussie ! Redirection vers vos résultats...");

        // On ouvre la fenêtre principale avec l'utilisateur stocké
    MainFrame mf = new MainFrame(this.currentUser); 
    mf.setVisible(true);
    
    this.dispose(); // On ferme le formulaire

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
    }
    }//GEN-LAST:event_btnInscrireActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
   RegisterFrame rf = new RegisterFrame();
    rf.setVisible(true);

    this.dispose(); 
    }//GEN-LAST:event_btnAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnInscrire;
    private javax.swing.JComboBox comboConcours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    }

