package ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import model.Candidat;

import dao.CandidatDao;
import dao.ConcoursDao;
import dao.ResultatDao;
import java.awt.CardLayout;
import java.awt.Container;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Concours;
import model.Resultat;
import model.Utilisateur;

/**
 *
 * @author hp
 */
public class MainFrame extends javax.swing.JFrame {
    private JPanel nomDeTonPanelCentral;
    
    private void loadCombos() {

    CandidatDao candidatDao = new CandidatDao();
    ConcoursDao concoursDao = new ConcoursDao();

    comboCandidat.removeAllItems();
    comboConcours.removeAllItems();
    java.util.Set<String> filieresUniques = new java.util.HashSet<>();
    java.util.Set<String> villesUniques = new java.util.HashSet<>();
    
    comboFiltreVille.removeAllItems();
    comboFiltreVille.addItem("Toutes les villes");

    // Ajout du filtre par filière
    if (comboFiltreFiliere != null) {
        comboFiltreFiliere.removeAllItems();
        comboFiltreFiliere.addItem("Toutes");
    }

    for (Candidat c : candidatDao.getAll()) {
        comboCandidat.addItem(c);
    }

    for (Concours c : concoursDao.getAll()) {
        comboConcours.addItem(c);
        if (c.getFiliere() != null && !c.getFiliere().isEmpty()) {
            filieresUniques.add(c.getFiliere());
        }
        
    }
    for (model.Candidat c : candidatDao.getAll()) {
        if (c.getVille() != null && !c.getVille().trim().isEmpty()) {
            villesUniques.add(c.getVille());
        }
    }
    for (String ville : villesUniques) {
        comboFiltreVille.addItem(ville);
    }
    
    if (comboFiltreFiliere != null) {
        for (String f : filieresUniques) {
            comboFiltreFiliere.addItem(f);
        }
    }
}
  
    private Utilisateur currentUser;
    private Object dateChooser;
    private Object GenererDecision;

   


    MainFrame() {
         initComponents();
        Utilisateur user = null;
    this.currentUser = user;
     if (!currentUser.getRole().equals("admin")) {

      jButton2.setVisible(false);
       jButton1.setVisible(false);
    }
    }
  

    /**
     * Creates new form MainFrame
     * @param user
     */
public MainFrame(Utilisateur user) {
    initComponents();
    this.setExtendedState(MainFrame.MAXIMIZED_BOTH);
    loadCombos(); 

    comboDecisionFilter.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Tous", "Admis", "Refusé", "En attente"}
        )
    );

    this.currentUser = user;

    if (!currentUser.getRole().equalsIgnoreCase("admin")) {

        // cacher menu
        jButton1.setVisible(false);
        jButton2.setVisible(false);

        // désactiver actions
        btnAjouterNote.setEnabled(false);
        btnSupprimerResultat.setEnabled(false);
        btnGenererDecision.setEnabled(false);

        // désactiver champs
        txtNote.setEditable(false);
        comboCandidat.setEnabled(false);
        comboConcours.setEnabled(false);

        // afficher panel Resultat
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "panelResultat");

        loadTableResultat();

    } else {

        loadTableCandidat();
        loadTableResultat();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        panelResultat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboCandidat = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        comboConcours = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        btnAjouterNote = new javax.swing.JButton();
        btnSupprimerResultat = new javax.swing.JButton();
        btnGenererDecision = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableResultat = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtRecherche = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comboDecisionFilter = new javax.swing.JComboBox();
        btnStats = new javax.swing.JButton();
        panelCandidat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVille = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNiveau = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnVider = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCandidat = new javax.swing.JTable();
        comboFiltreVille = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        panelConcours = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTitre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFiliere = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCapacite = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSeuil = new javax.swing.JTextField();
        btnAjouterConcours = new javax.swing.JButton();
        btnModifierConcours = new javax.swing.JButton();
        btnSupprimerConcours = new javax.swing.JButton();
        btnViderConcours = new javax.swing.JButton();
        jscrollpan = new javax.swing.JScrollPane();
        tableConcours = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        comboFiltreFiliere = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 204, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des Concours"));
        mainPanel.setForeground(new java.awt.Color(153, 153, 255));

        menuPanel.setBackground(new java.awt.Color(102, 0, 51));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setText("Candidats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setText("Concours");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setText("Résultats");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());

        panelResultat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("GESTION DES RÉSULTATS");

        jLabel13.setText("Candidat");

        comboCandidat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCandidatActionPerformed(evt);
            }
        });

        jLabel14.setText("Concours");

        comboConcours.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboConcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConcoursActionPerformed(evt);
            }
        });

        jLabel15.setText("Note");

        btnAjouterNote.setText("Ajouter");
        btnAjouterNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterNoteActionPerformed(evt);
            }
        });

        btnSupprimerResultat.setText("Supprimer Resultat");
        btnSupprimerResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerResultatActionPerformed(evt);
            }
        });

        btnGenererDecision.setText("Generer Decision");
        btnGenererDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenererDecisionActionPerformed(evt);
            }
        });

        tableResultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "candidat", "concours", "note", "Décision"
            }
        ));
        jScrollPane3.setViewportView(tableResultat);

        jLabel16.setText("Recherche :");

        txtRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheActionPerformed(evt);
            }
        });

        jLabel17.setText("Décision :");

        comboDecisionFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDecisionFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDecisionFilterActionPerformed(evt);
            }
        });

        btnStats.setText("Voir Statistiques");
        btnStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResultatLayout = new javax.swing.GroupLayout(panelResultat);
        panelResultat.setLayout(panelResultatLayout);
        panelResultatLayout.setHorizontalGroup(
            panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultatLayout.createSequentialGroup()
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelResultatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResultatLayout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResultatLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboConcours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelResultatLayout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboCandidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelResultatLayout.createSequentialGroup()
                                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(40, 40, 40)
                                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboDecisionFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRecherche))
                                .addGap(114, 114, 114)
                                .addComponent(btnStats))))
                    .addGroup(panelResultatLayout.createSequentialGroup()
                        .addComponent(btnAjouterNote, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimerResultat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenererDecision, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        panelResultatLayout.setVerticalGroup(
            panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultatLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCandidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(comboConcours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterNote)
                    .addComponent(btnSupprimerResultat)
                    .addComponent(btnGenererDecision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultatLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(comboDecisionFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelResultatLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnStats)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        contentPanel.add(panelResultat, "panelResultat");

        panelCandidat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("GESTION DES CANDIDATS");

        jLabel4.setText("Nom");

        jLabel5.setText("Email");

        jLabel6.setText("Ville");

        txtVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVilleActionPerformed(evt);
            }
        });

        jLabel7.setText("Niveau");

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnVider.setText("Vider");
        btnVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableCandidat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Email", "Ville", "Niveau"
            }
        ));
        jScrollPane1.setViewportView(tableCandidat);

        comboFiltreVille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFiltreVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltreVilleActionPerformed(evt);
            }
        });

        jLabel19.setText("filtrer par ville:");

        javax.swing.GroupLayout panelCandidatLayout = new javax.swing.GroupLayout(panelCandidat);
        panelCandidat.setLayout(panelCandidatLayout);
        panelCandidatLayout.setHorizontalGroup(
            panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCandidatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCandidatLayout.createSequentialGroup()
                        .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCandidatLayout.createSequentialGroup()
                                .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(panelCandidatLayout.createSequentialGroup()
                                .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCandidatLayout.createSequentialGroup()
                                .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addGap(40, 40, 40)
                                .addComponent(btnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addGap(49, 49, 49)
                                .addComponent(btnVider, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addGap(218, 218, 218))
                            .addGroup(panelCandidatLayout.createSequentialGroup()
                                .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVille)
                                    .addComponent(txtNom)
                                    .addComponent(txtEmail)
                                    .addComponent(txtNiveau, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(comboFiltreVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))))
                    .addGroup(panelCandidatLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(panelCandidatLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCandidatLayout.setVerticalGroup(
            panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCandidatLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCandidatLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVider))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(panelCandidatLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(comboFiltreVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        contentPanel.add(panelCandidat, "panelCandidat");

        panelConcours.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("GESTION DES CONCOURS");

        jLabel8.setText("Titre");

        txtTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitreActionPerformed(evt);
            }
        });

        jLabel9.setText("Date");

        jLabel10.setText("Filière");

        jLabel11.setText("Capacité");

        jLabel12.setText("Seuil");

        btnAjouterConcours.setText("Ajouter");
        btnAjouterConcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterConcoursActionPerformed(evt);
            }
        });

        btnModifierConcours.setText("Modifier");
        btnModifierConcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierConcoursActionPerformed(evt);
            }
        });

        btnSupprimerConcours.setText("Supprimer");
        btnSupprimerConcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerConcoursActionPerformed(evt);
            }
        });

        btnViderConcours.setText("Vider");
        btnViderConcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderConcoursActionPerformed(evt);
            }
        });

        jscrollpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jscrollpanMouseClicked(evt);
            }
        });

        tableConcours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titre", "Date", "Filière", "Capacité", "Seuil"
            }
        ));
        jscrollpan.setViewportView(tableConcours);

        jLabel18.setText("Filtrer par Filière:");

        comboFiltreFiliere.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFiltreFiliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltreFiliereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConcoursLayout = new javax.swing.GroupLayout(panelConcours);
        panelConcours.setLayout(panelConcoursLayout);
        panelConcoursLayout.setHorizontalGroup(
            panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConcoursLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelConcoursLayout.createSequentialGroup()
                .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConcoursLayout.createSequentialGroup()
                        .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouterConcours, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConcoursLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelConcoursLayout.createSequentialGroup()
                                        .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel10))
                                    .addComponent(txtSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelConcoursLayout.createSequentialGroup()
                                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel11))))
                            .addGroup(panelConcoursLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnModifierConcours, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSupprimerConcours)))
                        .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConcoursLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConcoursLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnViderConcours, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(39, 39, 39)
                .addComponent(comboFiltreFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(jscrollpan, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelConcoursLayout.setVerticalGroup(
            panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConcoursLayout.createSequentialGroup()
                .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelConcoursLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(txtFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(comboFiltreFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelConcoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterConcours)
                    .addComponent(btnModifierConcours)
                    .addComponent(btnSupprimerConcours)
                    .addComponent(btnViderConcours, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jscrollpan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        contentPanel.add(panelConcours, "panelConcours");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
CardLayout cl = (CardLayout) contentPanel.getLayout();
cl.show(contentPanel, "panelCandidat");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 CardLayout cl = (CardLayout) contentPanel.getLayout();
    cl.show(contentPanel, "panelResultat");

    // 2. Si c'est un simple utilisateur, on rafraîchit la table avec ses données
    if (currentUser != null && !"admin".equalsIgnoreCase(currentUser.getRole())) {
        loadTableResultat(); // Cette méthode doit filtrer par l'ID de currentUser
        
        // Sécurité : on recache les boutons au cas où
        btnAjouterNote.setVisible(false);
        btnSupprimerResultat.setVisible(false);
        btnGenererDecision.setVisible(false);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    CardLayout cl = (CardLayout) contentPanel.getLayout();
cl.show(contentPanel, "panelConcours");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
    
    int selectedRow = tableCandidat.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un candidat !");
        return;
    }

    int id = (int) tableCandidat.getValueAt(selectedRow, 0);

    Candidat c = new Candidat();
    c.setId(id);
    c.setNom(txtNom.getText());
    c.setEmail(txtEmail.getText());
    c.setVille(txtVille.getText());
    c.setNiveauEtude(txtNiveau.getText());

    CandidatDao dao = new CandidatDao();
    dao.update(c);

    loadTableCandidat();
    }//GEN-LAST:event_btnModifierActionPerformed

    private void txtVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVilleActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
       try {
        // Récupération des données
        String nom = txtNom.getText().trim();
        String email = txtEmail.getText().trim();
        String ville = txtVille.getText().trim();
        String niveau = txtNiveau.getText().trim();

        // Vérification des champs
        if (nom.isEmpty() || email.isEmpty() || ville.isEmpty() || niveau.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez remplir tous les champs !", 
                "Erreur", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Création objet
        Candidat c = new Candidat(nom, email, ville, niveau);

        // Appel DAO
        CandidatDao dao = new CandidatDao();
        dao.insert(c);

        JOptionPane.showMessageDialog(this, 
            "Candidat ajouté avec succès !", 
            "Succès", 
            JOptionPane.INFORMATION_MESSAGE);

        // Rafraîchir la table (si tu as une méthode loadTable())
        loadTableCandidat();

        // Vider les champs
        txtNom.setText("");
        txtEmail.setText("");
        txtVille.setText("");
        txtNiveau.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Erreur : " + e.getMessage(), 
            "Erreur", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void txtTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitreActionPerformed

    private void btnAjouterConcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterConcoursActionPerformed
    try {

    String titre = txtTitre.getText();
    String filiere = txtFiliere.getText();
    int capacite = Integer.parseInt(txtCapacite.getText());
    double seuil = Double.parseDouble(txtSeuil.getText());

    String dateText = txtDate.getText();

    java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateText);

    Concours c = new Concours();
    c.setTitre(titre);
    c.setDate(date);
    c.setFiliere(filiere);
    c.setCapacite(capacite);
    c.setSeuil(seuil);

    ConcoursDao dao = new ConcoursDao();
    dao.insert(c);

    loadTableConcours();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Format date : yyyy-MM-dd");
}
    }//GEN-LAST:event_btnAjouterConcoursActionPerformed

    private void btnGenererDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenererDecisionActionPerformed


 Concours concours = (Concours) comboConcours.getSelectedItem();
    if (concours == null) return;

    ResultatDao dao = new ResultatDao();
    dao.genererDecisions(concours.getId(), concours.getSeuil(), concours.getCapacite());

    // ASTUCE : Réinitialiser les filtres pour voir tout le monde après la génération
    txtRecherche.setText("");
    comboDecisionFilter.setSelectedItem("Tous");

    loadTableResultat(); // Maintenant le tableau devrait se remplir
    JOptionPane.showMessageDialog(this, "Décisions générées !");

    }//GEN-LAST:event_btnGenererDecisionActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
     int selectedRow = tableCandidat.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un candidat !");
        return;
    }

    int id = (int) tableCandidat.getValueAt(selectedRow, 0);

    CandidatDao dao = new CandidatDao();
    dao.delete(id);

    loadTableCandidat();
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderActionPerformed


    txtNom.setText("");
    txtEmail.setText("");
    txtVille.setText("");
    txtNiveau.setText("");

    tableCandidat.clearSelection();

    }//GEN-LAST:event_btnViderActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
       int selectedRow = tableCandidat.getSelectedRow();

txtNom.setText(tableCandidat.getValueAt(selectedRow, 1).toString());
txtEmail.setText(tableCandidat.getValueAt(selectedRow, 2).toString());
txtVille.setText(tableCandidat.getValueAt(selectedRow, 3).toString());
txtNiveau.setText(tableCandidat.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void btnAjouterNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterNoteActionPerformed
          Candidat candidat = (Candidat) comboCandidat.getSelectedItem();
    Concours concours = (Concours) comboConcours.getSelectedItem();

    double note = Double.parseDouble(txtNote.getText());

    Resultat r = new Resultat();
    r.setCandidatId(candidat.getId());
    r.setConcoursId(concours.getId());
    r.setNote(note);

    ResultatDao dao = new ResultatDao();
        try {
            dao.insert(r);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    loadTableResultat();
    }//GEN-LAST:event_btnAjouterNoteActionPerformed

    private void btnSupprimerResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerResultatActionPerformed
         int selectedRow = tableResultat.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un résultat !");
        return;
    }

    int id = (int) tableResultat.getValueAt(selectedRow, 0);

    ResultatDao dao = new ResultatDao();
    dao.delete(id);

    loadTableResultat();
    }//GEN-LAST:event_btnSupprimerResultatActionPerformed

    private void btnSupprimerConcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerConcoursActionPerformed


    int selectedRow = tableConcours.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un concours !");
        return;
    }

    int id = (int) tableConcours.getValueAt(selectedRow, 0);

    ConcoursDao dao = new ConcoursDao();
    dao.delete(id);

    loadTableConcours();
    viderChamps();


    }//GEN-LAST:event_btnSupprimerConcoursActionPerformed

    private void btnModifierConcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierConcoursActionPerformed
 
    int selectedRow = tableConcours.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un concours !");
        return;
    }

    try {

        int id = (int) tableConcours.getValueAt(selectedRow, 0);

        String titre = txtTitre.getText();
        String filiere = txtFiliere.getText();
        int capacite = Integer.parseInt(txtCapacite.getText());
        double seuil = Double.parseDouble(txtSeuil.getText());

        String dateText = txtDate.getText();
        java.util.Date date =
                new java.text.SimpleDateFormat("yyyy-MM-dd").parse(dateText);

        Concours c = new Concours(id, titre, date, filiere, capacite, seuil);

        ConcoursDao dao = new ConcoursDao();
        dao.update(c);

        loadTableConcours();
        viderChamps();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Format date : yyyy-MM-dd");
    }


    }//GEN-LAST:event_btnModifierConcoursActionPerformed

    private void btnViderConcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderConcoursActionPerformed
       txtTitre.setText("");
    txtDate.setText("");
    txtFiliere.setText("");
    txtCapacite.setText("");
    txtSeuil.setText("");

    tableConcours.clearSelection();
    }//GEN-LAST:event_btnViderConcoursActionPerformed

    private void jscrollpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jscrollpanMouseClicked
    int row = tableConcours.getSelectedRow();

    txtTitre.setText(tableConcours.getValueAt(row, 1).toString());
    txtDate.setText(tableConcours.getValueAt(row, 2).toString());
    txtFiliere.setText(tableConcours.getValueAt(row, 3).toString());
    txtCapacite.setText(tableConcours.getValueAt(row, 4).toString());
    txtSeuil.setText(tableConcours.getValueAt(row, 5).toString());
    }//GEN-LAST:event_jscrollpanMouseClicked

    private void txtRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheActionPerformed
     loadTableResultat();
    }//GEN-LAST:event_txtRechercheActionPerformed

    private void comboDecisionFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDecisionFilterActionPerformed
      loadTableResultat();
    }//GEN-LAST:event_comboDecisionFilterActionPerformed

    private void comboCandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCandidatActionPerformed

    }//GEN-LAST:event_comboCandidatActionPerformed

    private void comboConcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConcoursActionPerformed

    }//GEN-LAST:event_comboConcoursActionPerformed

    private void comboFiltreFiliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltreFiliereActionPerformed
if (comboFiltreFiliere.getSelectedItem() == null) {
        return;
    }

    String filiereSelectionnee = comboFiltreFiliere.getSelectedItem().toString();
    ConcoursDao concoursDao = new ConcoursDao();
    DefaultTableModel model = (DefaultTableModel) tableConcours.getModel();
    model.setRowCount(0); // On vide le tableau avant de le remplir

    List<Concours> liste;
    
    // Logique de filtrage
    if (filiereSelectionnee.equals("Toutes")) {
        liste = concoursDao.findAll(); // Utilise votre méthode findAll
    } else {
        liste = concoursDao.getByFiliere(filiereSelectionnee); // Utilise votre nouvelle méthode
    }

    // Remplissage de la table
    for (Concours c : liste) {
        model.addRow(new Object[]{
            c.getId(),
            c.getTitre(),
            c.getDate(),
            c.getFiliere(),
            c.getCapacite(),
            c.getSeuil()
        });
    }
    }//GEN-LAST:event_comboFiltreFiliereActionPerformed

    private void comboFiltreVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltreVilleActionPerformed
                                             
    // 1. Récupérer la ville sélectionnée
    if (comboFiltreVille.getSelectedItem() == null) return;
    String villeSelectionnee = comboFiltreVille.getSelectedItem().toString();
    
    // 2. Préparer le DAO et la liste
    CandidatDao dao = new CandidatDao();
    List<model.Candidat> liste;

    // 3. Charger les données selon le choix
    if (villeSelectionnee.equals("Toutes les villes") || villeSelectionnee.equals("")) {
        liste = dao.getAll();
    } else {
        liste = dao.getByVille(villeSelectionnee);
    }

    // 4. Mettre à jour le tableau JTable
    DefaultTableModel model = (DefaultTableModel) tableCandidat.getModel();
    model.setRowCount(0); // Vider le tableau

    for (model.Candidat c : liste) {
        model.addRow(new Object[]{
            c.getId(), 
            c.getNom(), 
            c.getEmail(), 
            c.getVille(), 
            c.getNiveauEtude()
        });
    }

    }//GEN-LAST:event_comboFiltreVilleActionPerformed

    private void btnStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsActionPerformed
StatistiquesFrame fenetreStats = new StatistiquesFrame(); 

// On l'affiche au centre de l'écran
fenetreStats.setVisible(true); 
fenetreStats.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnStatsActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAjouterConcours;
    private javax.swing.JButton btnAjouterNote;
    private javax.swing.JButton btnGenererDecision;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnModifierConcours;
    private javax.swing.JButton btnStats;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnSupprimerConcours;
    private javax.swing.JButton btnSupprimerResultat;
    private javax.swing.JButton btnVider;
    private javax.swing.JButton btnViderConcours;
    private javax.swing.JComboBox comboCandidat;
    private javax.swing.JComboBox comboConcours;
    private javax.swing.JComboBox comboDecisionFilter;
    private javax.swing.JComboBox comboFiltreFiliere;
    private javax.swing.JComboBox comboFiltreVille;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jscrollpan;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel panelCandidat;
    private javax.swing.JPanel panelConcours;
    private javax.swing.JPanel panelResultat;
    private javax.swing.JTable tableCandidat;
    private javax.swing.JTable tableConcours;
    private javax.swing.JTable tableResultat;
    private javax.swing.JTextField txtCapacite;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFiliere;
    private javax.swing.JTextField txtNiveau;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtRecherche;
    private javax.swing.JTextField txtSeuil;
    private javax.swing.JTextField txtTitre;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables

    private void loadTableCandidat() {
    try {
        CandidatDao dao = new CandidatDao();
        List<Candidat> liste = dao.getAll();   // Assure-toi que cette méthode existe

        DefaultTableModel model = (DefaultTableModel) tableCandidat.getModel();
        model.setRowCount(0); // vider table
        tableCandidat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
tableCandidat.getTableHeader().setReorderingAllowed(false); // Empêche de déplacer les colonnes

        for (Candidat c : liste) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNom(),
                c.getEmail(),
                c.getVille(),
                c.getNiveauEtude()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Erreur chargement table : " + e.getMessage());
    }
}
  private void loadComboCandidat() {

    comboCandidat.removeAllItems();

    CandidatDao dao = new CandidatDao();
    List<Candidat> liste = dao.getAll();

    for (Candidat c : liste) {
        comboCandidat.addItem(c); 
    }
}
    private void loadComboConcours() {

    comboConcours.removeAllItems();

    ConcoursDao dao = new ConcoursDao();
    List<Concours> liste = dao.getAll();

    for (Concours c : liste) {
      comboConcours.addItem(c);
    }
}

private void loadTableResultat() {
    ResultatDao rDao = new ResultatDao();
    
    
    // 1. Récupération des filtres
    String recherche = txtRecherche.getText().trim();
    String decision = (comboDecisionFilter.getSelectedItem() != null) ? 
                        comboDecisionFilter.getSelectedItem().toString() : "Tous";

    // 2. Récupération des données (via notre nouvelle méthode DTO)
    List<Object[]> liste = rDao.findFilteredWithNames(recherche, decision);

    // 3. Mise à jour du tableau
    DefaultTableModel model = (DefaultTableModel) tableResultat.getModel();
    model.setRowCount(0); // On vide tout avant de remplir

    for (Object[] ligne : liste) {
        // L'ordre ici doit être IDENTIQUE à l'étape 2
        model.addRow(ligne); 
    }
}
    private void loadTableConcours() {
        DefaultTableModel model = (DefaultTableModel) tableConcours.getModel();
    model.setRowCount(0);

    ConcoursDao dao = new ConcoursDao();
    List<Concours> liste = dao.getAll();

    for (Concours c : liste) {
        model.addRow(new Object[]{
            c.getId(),
            c.getTitre(),
            c.getDate(),
            c.getFiliere(),
            c.getCapacite(),
            c.getSeuil()
        });
    }
    }

    private void viderChamps() {
          txtTitre.setText("");
    txtDate.setText("");
    txtFiliere.setText("");
    txtCapacite.setText("");
    txtSeuil.setText("");

    tableConcours.clearSelection();
    }
    private void appliquerRole() {

    if (currentUser.getRole().equals("CANDIDAT")) {

       btnAjouterNote.setVisible(false);
       btnSupprimerResultat.setVisible(false);
       btnGenererDecision.setVisible(false);

    }
}
    public JPanel getMainContentPanel() {
    return this.nomDeTonPanelCentral;
}

    Container getMainPanel() {
      return mainPanel;
    }
    }
